### ISSUE TITLE
Alternative command profiles

### ISSUE THREAD

**Issue by grimnight** [trimclain/builder.nvim#4]
Would it be possible to have alternative command profiles?

Instead of the current:
```lua
commands = {
    go = "go run %",
},
```
It would be possible to have:
```lua
commands = {
    run = {
        go = "go run %",
    },
    build = {
        go = "go build -o $basename %",
    },
},
```
Which could then be used: `:Build commmand=run` or `:Build commmand=build`.

**Comment by trimclain** [comment]
Sounds like a good idea
