### ISSUE TITLE
Setting the output directory

### ISSUE THREAD

**Issue by Barret5Ocal** [trimclain/builder.nvim#9]
Is there a way to set the output directory of a build? when i build a project, it just seems to dump the binaries in the directory that I opened nvim in.

**Comment by trimclain** [comment]
Can you give me an example of the command you are using that needs this?

**Comment by Barret5Ocal** [comment]
Basically this is what i'm doing `cmd = "odin build $dir -debug"` I want to be able to set the output to a specific directory in my project folders

**Comment by trimclain** [comment]
There is no way to set the output directory of a build unless the command itself supports it. Builder is just executing given commands and displaying the output.

What you could do however is to add additional commands to the `cmd` string.

For `c` this could look like this:
```
commands = {
    c = "gcc % -o $basename.out && mkdir -p output && mv $basename.out output/$basename.out",
}
```
